package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/retrievercommunications/jasperserver-go/client/operations"
)

// Default jasperserver HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new jasperserver HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Jasperserver {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("localhost:8080", "/jasperserver/rest_v2/", []string{"http"})
	return New(transport, formats)
}

// New creates a new jasperserver client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Jasperserver {
	cli := new(Jasperserver)
	cli.Transport = transport

	cli.Operations = operations.New(transport, formats)

	return cli
}

// Jasperserver is a client for jasperserver
type Jasperserver struct {
	Operations *operations.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Jasperserver) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Operations.SetTransport(transport)

}
