package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewCreateGetReportInputParametersViaPostParams creates a new CreateGetReportInputParametersViaPostParams object
// with the default values initialized.
func NewCreateGetReportInputParametersViaPostParams() *CreateGetReportInputParametersViaPostParams {
	var (
		freshDataDefault bool = bool(false)
	)
	return &CreateGetReportInputParametersViaPostParams{
		FreshData: &freshDataDefault,
	}
}

/*CreateGetReportInputParametersViaPostParams contains all the parameters to send to the API endpoint
for the create get report input parameters via post operation typically these are written to a http.Request
*/
type CreateGetReportInputParametersViaPostParams struct {

	/*ExecutionID*/
	ExecutionID *string
	/*FreshData*/
	FreshData *bool
}

// WithExecutionID adds the executionId to the create get report input parameters via post params
func (o *CreateGetReportInputParametersViaPostParams) WithExecutionID(executionId *string) *CreateGetReportInputParametersViaPostParams {
	o.ExecutionID = executionId
	return o
}

// WithFreshData adds the freshData to the create get report input parameters via post params
func (o *CreateGetReportInputParametersViaPostParams) WithFreshData(freshData *bool) *CreateGetReportInputParametersViaPostParams {
	o.FreshData = freshData
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateGetReportInputParametersViaPostParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.ExecutionID != nil {

		// path param executionId
		if err := r.SetPathParam("executionId", *o.ExecutionID); err != nil {
			return err
		}

	}

	if o.FreshData != nil {

		// query param freshData
		var qrFreshData bool
		if o.FreshData != nil {
			qrFreshData = *o.FreshData
		}
		qFreshData := swag.FormatBool(qrFreshData)
		if qFreshData != "" {
			if err := r.SetQueryParam("freshData", qFreshData); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
