package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateExportReader is a Reader for the CreateExport structure.
type CreateExportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateExportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateExportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateExportOK creates a CreateExportOK with default headers values
func NewCreateExportOK() *CreateExportOK {
	return &CreateExportOK{}
}

/*CreateExportOK handles this case with default header values.

CreateExportOK create export o k
*/
type CreateExportOK struct {
}

func (o *CreateExportOK) Error() string {
	return fmt.Sprintf("[POST /{executionId}/exports][%d] createExportOK ", 200)
}

func (o *CreateExportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
