package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateGetThumbnailsFormEncodedParams creates a new CreateGetThumbnailsFormEncodedParams object
// with the default values initialized.
func NewCreateGetThumbnailsFormEncodedParams() *CreateGetThumbnailsFormEncodedParams {
	var ()
	return &CreateGetThumbnailsFormEncodedParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateGetThumbnailsFormEncodedParamsWithTimeout creates a new CreateGetThumbnailsFormEncodedParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateGetThumbnailsFormEncodedParamsWithTimeout(timeout time.Duration) *CreateGetThumbnailsFormEncodedParams {
	var ()
	return &CreateGetThumbnailsFormEncodedParams{

		timeout: timeout,
	}
}

/*CreateGetThumbnailsFormEncodedParams contains all the parameters to send to the API endpoint
for the create get thumbnails form encoded operation typically these are written to a http.Request
*/
type CreateGetThumbnailsFormEncodedParams struct {

	/*Accept*/
	Accept *string
	/*DefaultAllowed*/
	DefaultAllowed *bool

	timeout time.Duration
}

// WithAccept adds the accept to the create get thumbnails form encoded params
func (o *CreateGetThumbnailsFormEncodedParams) WithAccept(Accept *string) *CreateGetThumbnailsFormEncodedParams {
	o.Accept = Accept
	return o
}

// WithDefaultAllowed adds the defaultAllowed to the create get thumbnails form encoded params
func (o *CreateGetThumbnailsFormEncodedParams) WithDefaultAllowed(DefaultAllowed *bool) *CreateGetThumbnailsFormEncodedParams {
	o.DefaultAllowed = DefaultAllowed
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateGetThumbnailsFormEncodedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Accept != nil {

		// query param Accept
		var qrAccept string
		if o.Accept != nil {
			qrAccept = *o.Accept
		}
		qAccept := qrAccept
		if qAccept != "" {
			if err := r.SetQueryParam("Accept", qAccept); err != nil {
				return err
			}
		}

	}

	if o.DefaultAllowed != nil {

		// query param defaultAllowed
		var qrDefaultAllowed bool
		if o.DefaultAllowed != nil {
			qrDefaultAllowed = *o.DefaultAllowed
		}
		qDefaultAllowed := swag.FormatBool(qrDefaultAllowed)
		if qDefaultAllowed != "" {
			if err := r.SetQueryParam("defaultAllowed", qDefaultAllowed); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
