package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewCreateGetReportInputControlValuesViaPostParams creates a new CreateGetReportInputControlValuesViaPostParams object
// with the default values initialized.
func NewCreateGetReportInputControlValuesViaPostParams() *CreateGetReportInputControlValuesViaPostParams {
	var (
		freshDataDefault bool = bool(false)
	)
	return &CreateGetReportInputControlValuesViaPostParams{
		FreshData: &freshDataDefault,
	}
}

/*CreateGetReportInputControlValuesViaPostParams contains all the parameters to send to the API endpoint
for the create get report input control values via post operation typically these are written to a http.Request
*/
type CreateGetReportInputControlValuesViaPostParams struct {

	/*FreshData*/
	FreshData *bool
	/*InputControlIds*/
	InputControlIds *string
	/*ReportUnitURI*/
	ReportUnitURI *string
}

// WithFreshData adds the freshData to the create get report input control values via post params
func (o *CreateGetReportInputControlValuesViaPostParams) WithFreshData(freshData *bool) *CreateGetReportInputControlValuesViaPostParams {
	o.FreshData = freshData
	return o
}

// WithInputControlIds adds the inputControlIds to the create get report input control values via post params
func (o *CreateGetReportInputControlValuesViaPostParams) WithInputControlIds(inputControlIds *string) *CreateGetReportInputControlValuesViaPostParams {
	o.InputControlIds = inputControlIds
	return o
}

// WithReportUnitURI adds the reportUnitUri to the create get report input control values via post params
func (o *CreateGetReportInputControlValuesViaPostParams) WithReportUnitURI(reportUnitUri *string) *CreateGetReportInputControlValuesViaPostParams {
	o.ReportUnitURI = reportUnitUri
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateGetReportInputControlValuesViaPostParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.FreshData != nil {

		// query param freshData
		var qrFreshData bool
		if o.FreshData != nil {
			qrFreshData = *o.FreshData
		}
		qFreshData := swag.FormatBool(qrFreshData)
		if qFreshData != "" {
			if err := r.SetQueryParam("freshData", qFreshData); err != nil {
				return err
			}
		}

	}

	if o.InputControlIds != nil {

		// query param inputControlIds
		var qrInputControlIds string
		if o.InputControlIds != nil {
			qrInputControlIds = *o.InputControlIds
		}
		qInputControlIds := qrInputControlIds
		if qInputControlIds != "" {
			if err := r.SetQueryParam("inputControlIds", qInputControlIds); err != nil {
				return err
			}
		}

	}

	if o.ReportUnitURI != nil {

		// query param reportUnitURI
		var qrReportUnitURI string
		if o.ReportUnitURI != nil {
			qrReportUnitURI = *o.ReportUnitURI
		}
		qReportUnitURI := qrReportUnitURI
		if qReportUnitURI != "" {
			if err := r.SetQueryParam("reportUnitURI", qReportUnitURI); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
