package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateGetReportInputParametersViaPostParams creates a new CreateGetReportInputParametersViaPostParams object
// with the default values initialized.
func NewCreateGetReportInputParametersViaPostParams() *CreateGetReportInputParametersViaPostParams {
	var (
		freshDataDefault bool = bool(false)
	)
	return &CreateGetReportInputParametersViaPostParams{
		FreshData: &freshDataDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateGetReportInputParametersViaPostParamsWithTimeout creates a new CreateGetReportInputParametersViaPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateGetReportInputParametersViaPostParamsWithTimeout(timeout time.Duration) *CreateGetReportInputParametersViaPostParams {
	var (
		freshDataDefault bool = bool(false)
	)
	return &CreateGetReportInputParametersViaPostParams{
		FreshData: &freshDataDefault,

		timeout: timeout,
	}
}

/*CreateGetReportInputParametersViaPostParams contains all the parameters to send to the API endpoint
for the create get report input parameters via post operation typically these are written to a http.Request
*/
type CreateGetReportInputParametersViaPostParams struct {

	/*ExecutionID*/
	ExecutionID *string
	/*FreshData*/
	FreshData *bool

	timeout time.Duration
}

// WithExecutionID adds the executionId to the create get report input parameters via post params
func (o *CreateGetReportInputParametersViaPostParams) WithExecutionID(ExecutionID *string) *CreateGetReportInputParametersViaPostParams {
	o.ExecutionID = ExecutionID
	return o
}

// WithFreshData adds the freshData to the create get report input parameters via post params
func (o *CreateGetReportInputParametersViaPostParams) WithFreshData(FreshData *bool) *CreateGetReportInputParametersViaPostParams {
	o.FreshData = FreshData
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateGetReportInputParametersViaPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.ExecutionID != nil {

		// path param executionId
		if err := r.SetPathParam("executionId", *o.ExecutionID); err != nil {
			return err
		}

	}

	if o.FreshData != nil {

		// query param freshData
		var qrFreshData bool
		if o.FreshData != nil {
			qrFreshData = *o.FreshData
		}
		qFreshData := swag.FormatBool(qrFreshData)
		if qFreshData != "" {
			if err := r.SetQueryParam("freshData", qFreshData); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
