package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateConnectionParams creates a new CreateConnectionParams object
// with the default values initialized.
func NewCreateConnectionParams() *CreateConnectionParams {
	var ()
	return &CreateConnectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateConnectionParamsWithTimeout creates a new CreateConnectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateConnectionParamsWithTimeout(timeout time.Duration) *CreateConnectionParams {
	var ()
	return &CreateConnectionParams{

		timeout: timeout,
	}
}

/*CreateConnectionParams contains all the parameters to send to the API endpoint
for the create connection operation typically these are written to a http.Request
*/
type CreateConnectionParams struct {

	/*Accept*/
	Accept *string
	/*ContentType*/
	ContentType *string

	timeout time.Duration
}

// WithAccept adds the accept to the create connection params
func (o *CreateConnectionParams) WithAccept(Accept *string) *CreateConnectionParams {
	o.Accept = Accept
	return o
}

// WithContentType adds the contentType to the create connection params
func (o *CreateConnectionParams) WithContentType(ContentType *string) *CreateConnectionParams {
	o.ContentType = ContentType
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Accept != nil {

		// query param Accept
		var qrAccept string
		if o.Accept != nil {
			qrAccept = *o.Accept
		}
		qAccept := qrAccept
		if qAccept != "" {
			if err := r.SetQueryParam("Accept", qAccept); err != nil {
				return err
			}
		}

	}

	if o.ContentType != nil {

		// query param Content-Type
		var qrContentType string
		if o.ContentType != nil {
			qrContentType = *o.ContentType
		}
		qContentType := qrContentType
		if qContentType != "" {
			if err := r.SetQueryParam("Content-Type", qContentType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
