package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewCreateHandleDirectUploadParams creates a new CreateHandleDirectUploadParams object
// with the default values initialized.
func NewCreateHandleDirectUploadParams() *CreateHandleDirectUploadParams {
	var (
		includeAccessEventsDefault     bool = bool(false)
		includeAuditEventsDefault      bool = bool(false)
		includeMonitoringEventsDefault bool = bool(false)
		includeServerSettingsDefault   bool = bool(false)
		skipUserUpdateDefault          bool = bool(false)
		updateDefault                  bool = bool(false)
	)
	return &CreateHandleDirectUploadParams{
		IncludeAccessEvents:     &includeAccessEventsDefault,
		IncludeAuditEvents:      &includeAuditEventsDefault,
		IncludeMonitoringEvents: &includeMonitoringEventsDefault,
		IncludeServerSettings:   &includeServerSettingsDefault,
		SkipUserUpdate:          &skipUserUpdateDefault,
		Update:                  &updateDefault,
	}
}

/*CreateHandleDirectUploadParams contains all the parameters to send to the API endpoint
for the create handle direct upload operation typically these are written to a http.Request
*/
type CreateHandleDirectUploadParams struct {

	/*IncludeAccessEvents*/
	IncludeAccessEvents *bool
	/*IncludeAuditEvents*/
	IncludeAuditEvents *bool
	/*IncludeMonitoringEvents*/
	IncludeMonitoringEvents *bool
	/*IncludeServerSettings*/
	IncludeServerSettings *bool
	/*SkipUserUpdate*/
	SkipUserUpdate *bool
	/*Update*/
	Update *bool
}

// WithIncludeAccessEvents adds the includeAccessEvents to the create handle direct upload params
func (o *CreateHandleDirectUploadParams) WithIncludeAccessEvents(includeAccessEvents *bool) *CreateHandleDirectUploadParams {
	o.IncludeAccessEvents = includeAccessEvents
	return o
}

// WithIncludeAuditEvents adds the includeAuditEvents to the create handle direct upload params
func (o *CreateHandleDirectUploadParams) WithIncludeAuditEvents(includeAuditEvents *bool) *CreateHandleDirectUploadParams {
	o.IncludeAuditEvents = includeAuditEvents
	return o
}

// WithIncludeMonitoringEvents adds the includeMonitoringEvents to the create handle direct upload params
func (o *CreateHandleDirectUploadParams) WithIncludeMonitoringEvents(includeMonitoringEvents *bool) *CreateHandleDirectUploadParams {
	o.IncludeMonitoringEvents = includeMonitoringEvents
	return o
}

// WithIncludeServerSettings adds the includeServerSettings to the create handle direct upload params
func (o *CreateHandleDirectUploadParams) WithIncludeServerSettings(includeServerSettings *bool) *CreateHandleDirectUploadParams {
	o.IncludeServerSettings = includeServerSettings
	return o
}

// WithSkipUserUpdate adds the skipUserUpdate to the create handle direct upload params
func (o *CreateHandleDirectUploadParams) WithSkipUserUpdate(skipUserUpdate *bool) *CreateHandleDirectUploadParams {
	o.SkipUserUpdate = skipUserUpdate
	return o
}

// WithUpdate adds the update to the create handle direct upload params
func (o *CreateHandleDirectUploadParams) WithUpdate(update *bool) *CreateHandleDirectUploadParams {
	o.Update = update
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateHandleDirectUploadParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.IncludeAccessEvents != nil {

		// query param includeAccessEvents
		var qrIncludeAccessEvents bool
		if o.IncludeAccessEvents != nil {
			qrIncludeAccessEvents = *o.IncludeAccessEvents
		}
		qIncludeAccessEvents := swag.FormatBool(qrIncludeAccessEvents)
		if qIncludeAccessEvents != "" {
			if err := r.SetQueryParam("includeAccessEvents", qIncludeAccessEvents); err != nil {
				return err
			}
		}

	}

	if o.IncludeAuditEvents != nil {

		// query param includeAuditEvents
		var qrIncludeAuditEvents bool
		if o.IncludeAuditEvents != nil {
			qrIncludeAuditEvents = *o.IncludeAuditEvents
		}
		qIncludeAuditEvents := swag.FormatBool(qrIncludeAuditEvents)
		if qIncludeAuditEvents != "" {
			if err := r.SetQueryParam("includeAuditEvents", qIncludeAuditEvents); err != nil {
				return err
			}
		}

	}

	if o.IncludeMonitoringEvents != nil {

		// query param includeMonitoringEvents
		var qrIncludeMonitoringEvents bool
		if o.IncludeMonitoringEvents != nil {
			qrIncludeMonitoringEvents = *o.IncludeMonitoringEvents
		}
		qIncludeMonitoringEvents := swag.FormatBool(qrIncludeMonitoringEvents)
		if qIncludeMonitoringEvents != "" {
			if err := r.SetQueryParam("includeMonitoringEvents", qIncludeMonitoringEvents); err != nil {
				return err
			}
		}

	}

	if o.IncludeServerSettings != nil {

		// query param includeServerSettings
		var qrIncludeServerSettings bool
		if o.IncludeServerSettings != nil {
			qrIncludeServerSettings = *o.IncludeServerSettings
		}
		qIncludeServerSettings := swag.FormatBool(qrIncludeServerSettings)
		if qIncludeServerSettings != "" {
			if err := r.SetQueryParam("includeServerSettings", qIncludeServerSettings); err != nil {
				return err
			}
		}

	}

	if o.SkipUserUpdate != nil {

		// query param skipUserUpdate
		var qrSkipUserUpdate bool
		if o.SkipUserUpdate != nil {
			qrSkipUserUpdate = *o.SkipUserUpdate
		}
		qSkipUserUpdate := swag.FormatBool(qrSkipUserUpdate)
		if qSkipUserUpdate != "" {
			if err := r.SetQueryParam("skipUserUpdate", qSkipUserUpdate); err != nil {
				return err
			}
		}

	}

	if o.Update != nil {

		// query param update
		var qrUpdate bool
		if o.Update != nil {
			qrUpdate = *o.Update
		}
		qUpdate := swag.FormatBool(qrUpdate)
		if qUpdate != "" {
			if err := r.SetQueryParam("update", qUpdate); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
