package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// CreateFileViaFormReader is a Reader for the CreateFileViaForm structure.
type CreateFileViaFormReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateFileViaFormReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateFileViaFormOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateFileViaFormOK creates a CreateFileViaFormOK with default headers values
func NewCreateFileViaFormOK() *CreateFileViaFormOK {
	return &CreateFileViaFormOK{}
}

/*CreateFileViaFormOK handles this case with default header values.

CreateFileViaFormOK create file via form o k
*/
type CreateFileViaFormOK struct {
}

func (o *CreateFileViaFormOK) Error() string {
	return fmt.Sprintf("[POST /{uri: .+}][%d] createFileViaFormOK ", 200)
}

func (o *CreateFileViaFormOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
