package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// CreateResumeReader is a Reader for the CreateResume structure.
type CreateResumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateResumeReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateResumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateResumeOK creates a CreateResumeOK with default headers values
func NewCreateResumeOK() *CreateResumeOK {
	return &CreateResumeOK{}
}

/*CreateResumeOK handles this case with default header values.

CreateResumeOK create resume o k
*/
type CreateResumeOK struct {
}

func (o *CreateResumeOK) Error() string {
	return fmt.Sprintf("[POST /resume][%d] createResumeOK ", 200)
}

func (o *CreateResumeOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
