package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewCreateConnectionParams creates a new CreateConnectionParams object
// with the default values initialized.
func NewCreateConnectionParams() *CreateConnectionParams {
	var ()
	return &CreateConnectionParams{}
}

/*CreateConnectionParams contains all the parameters to send to the API endpoint
for the create connection operation typically these are written to a http.Request
*/
type CreateConnectionParams struct {

	/*Accept*/
	Accept *string
	/*ContentType*/
	ContentType *string
}

// WithAccept adds the accept to the create connection params
func (o *CreateConnectionParams) WithAccept(accept *string) *CreateConnectionParams {
	o.Accept = accept
	return o
}

// WithContentType adds the contentType to the create connection params
func (o *CreateConnectionParams) WithContentType(contentType *string) *CreateConnectionParams {
	o.ContentType = contentType
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateConnectionParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Accept != nil {

		// query param Accept
		var qrAccept string
		if o.Accept != nil {
			qrAccept = *o.Accept
		}
		qAccept := qrAccept
		if qAccept != "" {
			if err := r.SetQueryParam("Accept", qAccept); err != nil {
				return err
			}
		}

	}

	if o.ContentType != nil {

		// query param Content-Type
		var qrContentType string
		if o.ContentType != nil {
			qrContentType = *o.ContentType
		}
		qContentType := qrContentType
		if qContentType != "" {
			if err := r.SetQueryParam("Content-Type", qContentType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
