package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateGetReportOutputMetadataReader is a Reader for the CreateGetReportOutputMetadata structure.
type CreateGetReportOutputMetadataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateGetReportOutputMetadataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateGetReportOutputMetadataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateGetReportOutputMetadataOK creates a CreateGetReportOutputMetadataOK with default headers values
func NewCreateGetReportOutputMetadataOK() *CreateGetReportOutputMetadataOK {
	return &CreateGetReportOutputMetadataOK{}
}

/*CreateGetReportOutputMetadataOK handles this case with default header values.

CreateGetReportOutputMetadataOK create get report output metadata o k
*/
type CreateGetReportOutputMetadataOK struct {
}

func (o *CreateGetReportOutputMetadataOK) Error() string {
	return fmt.Sprintf("[POST /reportExecutions][%d] createGetReportOutputMetadataOK ", 200)
}

func (o *CreateGetReportOutputMetadataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
