package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreateFileViaFormInRootReader is a Reader for the CreateFileViaFormInRoot structure.
type CreateFileViaFormInRootReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateFileViaFormInRootReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateFileViaFormInRootOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateFileViaFormInRootOK creates a CreateFileViaFormInRootOK with default headers values
func NewCreateFileViaFormInRootOK() *CreateFileViaFormInRootOK {
	return &CreateFileViaFormInRootOK{}
}

/*CreateFileViaFormInRootOK handles this case with default header values.

CreateFileViaFormInRootOK create file via form in root o k
*/
type CreateFileViaFormInRootOK struct {
}

func (o *CreateFileViaFormInRootOK) Error() string {
	return fmt.Sprintf("[POST /resources][%d] createFileViaFormInRootOK ", 200)
}

func (o *CreateFileViaFormInRootOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
