package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// CreatePermissionReader is a Reader for the CreatePermission structure.
type CreatePermissionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreatePermissionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreatePermissionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreatePermissionOK creates a CreatePermissionOK with default headers values
func NewCreatePermissionOK() *CreatePermissionOK {
	return &CreatePermissionOK{}
}

/*CreatePermissionOK handles this case with default header values.

CreatePermissionOK create permission o k
*/
type CreatePermissionOK struct {
}

func (o *CreatePermissionOK) Error() string {
	return fmt.Sprintf("[POST /permissions][%d] createPermissionOK ", 200)
}

func (o *CreatePermissionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
