package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// CreateNewTaskReader is a Reader for the CreateNewTask structure.
type CreateNewTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *CreateNewTaskReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateNewTaskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateNewTaskOK creates a CreateNewTaskOK with default headers values
func NewCreateNewTaskOK() *CreateNewTaskOK {
	return &CreateNewTaskOK{}
}

/*CreateNewTaskOK handles this case with default header values.

CreateNewTaskOK create new task o k
*/
type CreateNewTaskOK struct {
}

func (o *CreateNewTaskOK) Error() string {
	return fmt.Sprintf("[POST /export][%d] createNewTaskOK ", 200)
}

func (o *CreateNewTaskOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
