package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateExportParams creates a new CreateExportParams object
// with the default values initialized.
func NewCreateExportParams() *CreateExportParams {
	var ()
	return &CreateExportParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateExportParamsWithTimeout creates a new CreateExportParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateExportParamsWithTimeout(timeout time.Duration) *CreateExportParams {
	var ()
	return &CreateExportParams{

		timeout: timeout,
	}
}

/*CreateExportParams contains all the parameters to send to the API endpoint
for the create export operation typically these are written to a http.Request
*/
type CreateExportParams struct {

	/*ExecutionID*/
	ExecutionID *string

	timeout time.Duration
}

// WithExecutionID adds the executionId to the create export params
func (o *CreateExportParams) WithExecutionID(ExecutionID *string) *CreateExportParams {
	o.ExecutionID = ExecutionID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *CreateExportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.ExecutionID != nil {

		// path param executionId
		if err := r.SetPathParam("executionId", *o.ExecutionID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
