package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateGetReportOutputMetadataParams creates a new CreateGetReportOutputMetadataParams object
// with the default values initialized.
func NewCreateGetReportOutputMetadataParams() *CreateGetReportOutputMetadataParams {

	return &CreateGetReportOutputMetadataParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateGetReportOutputMetadataParamsWithTimeout creates a new CreateGetReportOutputMetadataParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateGetReportOutputMetadataParamsWithTimeout(timeout time.Duration) *CreateGetReportOutputMetadataParams {

	return &CreateGetReportOutputMetadataParams{

		timeout: timeout,
	}
}

/*CreateGetReportOutputMetadataParams contains all the parameters to send to the API endpoint
for the create get report output metadata operation typically these are written to a http.Request
*/
type CreateGetReportOutputMetadataParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *CreateGetReportOutputMetadataParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
