package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// DeletePermissionsEntryPointReader is a Reader for the DeletePermissionsEntryPoint structure.
type DeletePermissionsEntryPointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeletePermissionsEntryPointReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeletePermissionsEntryPointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeletePermissionsEntryPointOK creates a DeletePermissionsEntryPointOK with default headers values
func NewDeletePermissionsEntryPointOK() *DeletePermissionsEntryPointOK {
	return &DeletePermissionsEntryPointOK{}
}

/*DeletePermissionsEntryPointOK handles this case with default header values.

DeletePermissionsEntryPointOK delete permissions entry point o k
*/
type DeletePermissionsEntryPointOK struct {
}

func (o *DeletePermissionsEntryPointOK) Error() string {
	return fmt.Sprintf("[DELETE /{uri:.+}][%d] deletePermissionsEntryPointOK ", 200)
}

func (o *DeletePermissionsEntryPointOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
