package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteResourceReader is a Reader for the DeleteResource structure.
type DeleteResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteResourceOK creates a DeleteResourceOK with default headers values
func NewDeleteResourceOK() *DeleteResourceOK {
	return &DeleteResourceOK{}
}

/*DeleteResourceOK handles this case with default header values.

DeleteResourceOK delete resource o k
*/
type DeleteResourceOK struct {
}

func (o *DeleteResourceOK) Error() string {
	return fmt.Sprintf("[DELETE /{uri: .+}][%d] deleteResourceOK ", 200)
}

func (o *DeleteResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
