package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteAttributeParams creates a new DeleteAttributeParams object
// with the default values initialized.
func NewDeleteAttributeParams() *DeleteAttributeParams {
	var ()
	return &DeleteAttributeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAttributeParamsWithTimeout creates a new DeleteAttributeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteAttributeParamsWithTimeout(timeout time.Duration) *DeleteAttributeParams {
	var ()
	return &DeleteAttributeParams{

		timeout: timeout,
	}
}

/*DeleteAttributeParams contains all the parameters to send to the API endpoint
for the delete attribute operation typically these are written to a http.Request
*/
type DeleteAttributeParams struct {

	/*AttrName*/
	AttrName *string

	timeout time.Duration
}

// WithAttrName adds the attrName to the delete attribute params
func (o *DeleteAttributeParams) WithAttrName(AttrName *string) *DeleteAttributeParams {
	o.AttrName = AttrName
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAttributeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.AttrName != nil {

		// path param attrName
		if err := r.SetPathParam("attrName", *o.AttrName); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
