package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewDeleteClearCacheParams creates a new DeleteClearCacheParams object
// with the default values initialized.
func NewDeleteClearCacheParams() *DeleteClearCacheParams {
	var ()
	return &DeleteClearCacheParams{}
}

/*DeleteClearCacheParams contains all the parameters to send to the API endpoint
for the delete clear cache operation typically these are written to a http.Request
*/
type DeleteClearCacheParams struct {

	/*CacheID*/
	CacheID *string
}

// WithCacheID adds the cacheId to the delete clear cache params
func (o *DeleteClearCacheParams) WithCacheID(cacheId *string) *DeleteClearCacheParams {
	o.CacheID = cacheId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteClearCacheParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.CacheID != nil {

		// path param cacheId
		if err := r.SetPathParam("cacheId", *o.CacheID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
