package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// DeleteAttributeReader is a Reader for the DeleteAttribute structure.
type DeleteAttributeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteAttributeReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAttributeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteAttributeOK creates a DeleteAttributeOK with default headers values
func NewDeleteAttributeOK() *DeleteAttributeOK {
	return &DeleteAttributeOK{}
}

/*DeleteAttributeOK handles this case with default header values.

DeleteAttributeOK delete attribute o k
*/
type DeleteAttributeOK struct {
}

func (o *DeleteAttributeOK) Error() string {
	return fmt.Sprintf("[DELETE /{attrName}][%d] deleteAttributeOK ", 200)
}

func (o *DeleteAttributeOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
