package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteNameAttributesReader is a Reader for the DeleteNameAttributes structure.
type DeleteNameAttributesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *DeleteNameAttributesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteNameAttributesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteNameAttributesOK creates a DeleteNameAttributesOK with default headers values
func NewDeleteNameAttributesOK() *DeleteNameAttributesOK {
	return &DeleteNameAttributesOK{}
}

/*DeleteNameAttributesOK handles this case with default header values.

DeleteNameAttributesOK delete name attributes o k
*/
type DeleteNameAttributesOK struct {
}

func (o *DeleteNameAttributesOK) Error() string {
	return fmt.Sprintf("[DELETE /{name}/attributes][%d] deleteNameAttributesOK ", 200)
}

func (o *DeleteNameAttributesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
