package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteJobParams creates a new DeleteJobParams object
// with the default values initialized.
func NewDeleteJobParams() *DeleteJobParams {
	var ()
	return &DeleteJobParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteJobParamsWithTimeout creates a new DeleteJobParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteJobParamsWithTimeout(timeout time.Duration) *DeleteJobParams {
	var ()
	return &DeleteJobParams{

		timeout: timeout,
	}
}

/*DeleteJobParams contains all the parameters to send to the API endpoint
for the delete job operation typically these are written to a http.Request
*/
type DeleteJobParams struct {

	/*ID*/
	ID *int64

	timeout time.Duration
}

// WithID adds the id to the delete job params
func (o *DeleteJobParams) WithID(ID *int64) *DeleteJobParams {
	o.ID = ID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteJobParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.ID != nil {

		// query param id
		var qrID int64
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := swag.FormatInt64(qrID)
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
