package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteNameAttributesParams creates a new DeleteNameAttributesParams object
// with the default values initialized.
func NewDeleteNameAttributesParams() *DeleteNameAttributesParams {
	var ()
	return &DeleteNameAttributesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteNameAttributesParamsWithTimeout creates a new DeleteNameAttributesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteNameAttributesParamsWithTimeout(timeout time.Duration) *DeleteNameAttributesParams {
	var ()
	return &DeleteNameAttributesParams{

		timeout: timeout,
	}
}

/*DeleteNameAttributesParams contains all the parameters to send to the API endpoint
for the delete name attributes operation typically these are written to a http.Request
*/
type DeleteNameAttributesParams struct {

	/*Name*/
	Name *string

	timeout time.Duration
}

// WithName adds the name to the delete name attributes params
func (o *DeleteNameAttributesParams) WithName(Name *string) *DeleteNameAttributesParams {
	o.Name = Name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteNameAttributesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Name != nil {

		// path param name
		if err := r.SetPathParam("name", *o.Name); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
