package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewDeleteAttributeParams creates a new DeleteAttributeParams object
// with the default values initialized.
func NewDeleteAttributeParams() *DeleteAttributeParams {
	var ()
	return &DeleteAttributeParams{}
}

/*DeleteAttributeParams contains all the parameters to send to the API endpoint
for the delete attribute operation typically these are written to a http.Request
*/
type DeleteAttributeParams struct {

	/*AttrName*/
	AttrName *string
}

// WithAttrName adds the attrName to the delete attribute params
func (o *DeleteAttributeParams) WithAttrName(attrName *string) *DeleteAttributeParams {
	o.AttrName = attrName
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAttributeParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.AttrName != nil {

		// path param attrName
		if err := r.SetPathParam("attrName", *o.AttrName); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
