package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAttributesParams creates a new GetAttributesParams object
// with the default values initialized.
func NewGetAttributesParams() *GetAttributesParams {
	var ()
	return &GetAttributesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAttributesParamsWithTimeout creates a new GetAttributesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAttributesParamsWithTimeout(timeout time.Duration) *GetAttributesParams {
	var ()
	return &GetAttributesParams{

		timeout: timeout,
	}
}

/*GetAttributesParams contains all the parameters to send to the API endpoint
for the get attributes operation typically these are written to a http.Request
*/
type GetAttributesParams struct {

	/*Accept*/
	Accept *string
	/*Embedded*/
	Embedded *string
	/*Name*/
	Name *string

	timeout time.Duration
}

// WithAccept adds the accept to the get attributes params
func (o *GetAttributesParams) WithAccept(Accept *string) *GetAttributesParams {
	o.Accept = Accept
	return o
}

// WithEmbedded adds the embedded to the get attributes params
func (o *GetAttributesParams) WithEmbedded(Embedded *string) *GetAttributesParams {
	o.Embedded = Embedded
	return o
}

// WithName adds the name to the get attributes params
func (o *GetAttributesParams) WithName(Name *string) *GetAttributesParams {
	o.Name = Name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetAttributesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Accept != nil {

		// query param Accept
		var qrAccept string
		if o.Accept != nil {
			qrAccept = *o.Accept
		}
		qAccept := qrAccept
		if qAccept != "" {
			if err := r.SetQueryParam("Accept", qAccept); err != nil {
				return err
			}
		}

	}

	if o.Embedded != nil {

		// query param _embedded
		var qrEmbedded string
		if o.Embedded != nil {
			qrEmbedded = *o.Embedded
		}
		qEmbedded := qrEmbedded
		if qEmbedded != "" {
			if err := r.SetQueryParam("_embedded", qEmbedded); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
