package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetJdbcDriversHipermediaRepresentationReader is a Reader for the GetJdbcDriversHipermediaRepresentation structure.
type GetJdbcDriversHipermediaRepresentationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetJdbcDriversHipermediaRepresentationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetJdbcDriversHipermediaRepresentationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetJdbcDriversHipermediaRepresentationOK creates a GetJdbcDriversHipermediaRepresentationOK with default headers values
func NewGetJdbcDriversHipermediaRepresentationOK() *GetJdbcDriversHipermediaRepresentationOK {
	return &GetJdbcDriversHipermediaRepresentationOK{}
}

/*GetJdbcDriversHipermediaRepresentationOK handles this case with default header values.

GetJdbcDriversHipermediaRepresentationOK get jdbc drivers hipermedia representation o k
*/
type GetJdbcDriversHipermediaRepresentationOK struct {
}

func (o *GetJdbcDriversHipermediaRepresentationOK) Error() string {
	return fmt.Sprintf("[GET /jdbcDrivers][%d] getJdbcDriversHipermediaRepresentationOK ", 200)
}

func (o *GetJdbcDriversHipermediaRepresentationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
