package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDownloadFileParams creates a new GetDownloadFileParams object
// with the default values initialized.
func NewGetDownloadFileParams() *GetDownloadFileParams {
	var ()
	return &GetDownloadFileParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDownloadFileParamsWithTimeout creates a new GetDownloadFileParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDownloadFileParamsWithTimeout(timeout time.Duration) *GetDownloadFileParams {
	var ()
	return &GetDownloadFileParams{

		timeout: timeout,
	}
}

/*GetDownloadFileParams contains all the parameters to send to the API endpoint
for the get download file operation typically these are written to a http.Request
*/
type GetDownloadFileParams struct {

	/*ID*/
	ID *string
	/*Name*/
	Name *string

	timeout time.Duration
}

// WithID adds the id to the get download file params
func (o *GetDownloadFileParams) WithID(ID *string) *GetDownloadFileParams {
	o.ID = ID
	return o
}

// WithName adds the name to the get download file params
func (o *GetDownloadFileParams) WithName(Name *string) *GetDownloadFileParams {
	o.Name = Name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetDownloadFileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.ID != nil {

		// path param id
		if err := r.SetPathParam("id", *o.ID); err != nil {
			return err
		}

	}

	if o.Name != nil {

		// path param name
		if err := r.SetPathParam("name", *o.Name); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
