package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetSpecificAttributeParams creates a new GetSpecificAttributeParams object
// with the default values initialized.
func NewGetSpecificAttributeParams() *GetSpecificAttributeParams {
	var ()
	return &GetSpecificAttributeParams{}
}

/*GetSpecificAttributeParams contains all the parameters to send to the API endpoint
for the get specific attribute operation typically these are written to a http.Request
*/
type GetSpecificAttributeParams struct {

	/*Accept*/
	Accept *string
	/*Embedded*/
	Embedded *string
	/*AttrName*/
	AttrName *string
}

// WithAccept adds the accept to the get specific attribute params
func (o *GetSpecificAttributeParams) WithAccept(accept *string) *GetSpecificAttributeParams {
	o.Accept = accept
	return o
}

// WithEmbedded adds the embedded to the get specific attribute params
func (o *GetSpecificAttributeParams) WithEmbedded(embedded *string) *GetSpecificAttributeParams {
	o.Embedded = embedded
	return o
}

// WithAttrName adds the attrName to the get specific attribute params
func (o *GetSpecificAttributeParams) WithAttrName(attrName *string) *GetSpecificAttributeParams {
	o.AttrName = attrName
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSpecificAttributeParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Accept != nil {

		// query param Accept
		var qrAccept string
		if o.Accept != nil {
			qrAccept = *o.Accept
		}
		qAccept := qrAccept
		if qAccept != "" {
			if err := r.SetQueryParam("Accept", qAccept); err != nil {
				return err
			}
		}

	}

	if o.Embedded != nil {

		// query param _embedded
		var qrEmbedded string
		if o.Embedded != nil {
			qrEmbedded = *o.Embedded
		}
		qEmbedded := qrEmbedded
		if qEmbedded != "" {
			if err := r.SetQueryParam("_embedded", qEmbedded); err != nil {
				return err
			}
		}

	}

	if o.AttrName != nil {

		// path param attrName
		if err := r.SetPathParam("attrName", *o.AttrName); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
