package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetExportExecutionStatusObjectReader is a Reader for the GetExportExecutionStatusObject structure.
type GetExportExecutionStatusObjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetExportExecutionStatusObjectReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetExportExecutionStatusObjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetExportExecutionStatusObjectOK creates a GetExportExecutionStatusObjectOK with default headers values
func NewGetExportExecutionStatusObjectOK() *GetExportExecutionStatusObjectOK {
	return &GetExportExecutionStatusObjectOK{}
}

/*GetExportExecutionStatusObjectOK handles this case with default header values.

GetExportExecutionStatusObjectOK get export execution status object o k
*/
type GetExportExecutionStatusObjectOK struct {
}

func (o *GetExportExecutionStatusObjectOK) Error() string {
	return fmt.Sprintf("[GET /{executionId}/exports/{exportId}/status][%d] getExportExecutionStatusObjectOK ", 200)
}

func (o *GetExportExecutionStatusObjectOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
