package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetPermissionsEntryPointReader is a Reader for the GetPermissionsEntryPoint structure.
type GetPermissionsEntryPointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetPermissionsEntryPointReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetPermissionsEntryPointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPermissionsEntryPointOK creates a GetPermissionsEntryPointOK with default headers values
func NewGetPermissionsEntryPointOK() *GetPermissionsEntryPointOK {
	return &GetPermissionsEntryPointOK{}
}

/*GetPermissionsEntryPointOK handles this case with default header values.

GetPermissionsEntryPointOK get permissions entry point o k
*/
type GetPermissionsEntryPointOK struct {
}

func (o *GetPermissionsEntryPointOK) Error() string {
	return fmt.Sprintf("[GET /{uri:.+}][%d] getPermissionsEntryPointOK ", 200)
}

func (o *GetPermissionsEntryPointOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
