package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetConnectionDetailsParams creates a new GetConnectionDetailsParams object
// with the default values initialized.
func NewGetConnectionDetailsParams() *GetConnectionDetailsParams {
	var ()
	return &GetConnectionDetailsParams{}
}

/*GetConnectionDetailsParams contains all the parameters to send to the API endpoint
for the get connection details operation typically these are written to a http.Request
*/
type GetConnectionDetailsParams struct {

	/*UUID*/
	UUID *string
}

// WithUUID adds the uuid to the get connection details params
func (o *GetConnectionDetailsParams) WithUUID(uuid *string) *GetConnectionDetailsParams {
	o.UUID = uuid
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetConnectionDetailsParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.UUID != nil {

		// path param uuid
		if err := r.SetPathParam("uuid", *o.UUID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
