package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetJobWithProcessedParametersReader is a Reader for the GetJobWithProcessedParameters structure.
type GetJobWithProcessedParametersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetJobWithProcessedParametersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetJobWithProcessedParametersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetJobWithProcessedParametersOK creates a GetJobWithProcessedParametersOK with default headers values
func NewGetJobWithProcessedParametersOK() *GetJobWithProcessedParametersOK {
	return &GetJobWithProcessedParametersOK{}
}

/*GetJobWithProcessedParametersOK handles this case with default header values.

GetJobWithProcessedParametersOK get job with processed parameters o k
*/
type GetJobWithProcessedParametersOK struct {
}

func (o *GetJobWithProcessedParametersOK) Error() string {
	return fmt.Sprintf("[GET /{id: \\d+}][%d] getJobWithProcessedParametersOK ", 200)
}

func (o *GetJobWithProcessedParametersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
