package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetStateOfTheTaskReader is a Reader for the GetStateOfTheTask structure.
type GetStateOfTheTaskReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetStateOfTheTaskReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetStateOfTheTaskOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetStateOfTheTaskOK creates a GetStateOfTheTaskOK with default headers values
func NewGetStateOfTheTaskOK() *GetStateOfTheTaskOK {
	return &GetStateOfTheTaskOK{}
}

/*GetStateOfTheTaskOK handles this case with default header values.

GetStateOfTheTaskOK get state of the task o k
*/
type GetStateOfTheTaskOK struct {
}

func (o *GetStateOfTheTaskOK) Error() string {
	return fmt.Sprintf("[GET /{id}/state][%d] getStateOfTheTaskOK ", 200)
}

func (o *GetStateOfTheTaskOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
