package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCalendarByNameParams creates a new GetCalendarByNameParams object
// with the default values initialized.
func NewGetCalendarByNameParams() *GetCalendarByNameParams {
	var ()
	return &GetCalendarByNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCalendarByNameParamsWithTimeout creates a new GetCalendarByNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCalendarByNameParamsWithTimeout(timeout time.Duration) *GetCalendarByNameParams {
	var ()
	return &GetCalendarByNameParams{

		timeout: timeout,
	}
}

/*GetCalendarByNameParams contains all the parameters to send to the API endpoint
for the get calendar by name operation typically these are written to a http.Request
*/
type GetCalendarByNameParams struct {

	/*CalendarName*/
	CalendarName *string

	timeout time.Duration
}

// WithCalendarName adds the calendarName to the get calendar by name params
func (o *GetCalendarByNameParams) WithCalendarName(CalendarName *string) *GetCalendarByNameParams {
	o.CalendarName = CalendarName
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetCalendarByNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.CalendarName != nil {

		// path param calendarName
		if err := r.SetPathParam("calendarName", *o.CalendarName); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
