package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetSettingsGroupReader is a Reader for the GetSettingsGroup structure.
type GetSettingsGroupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetSettingsGroupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSettingsGroupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSettingsGroupOK creates a GetSettingsGroupOK with default headers values
func NewGetSettingsGroupOK() *GetSettingsGroupOK {
	return &GetSettingsGroupOK{}
}

/*GetSettingsGroupOK handles this case with default header values.

GetSettingsGroupOK get settings group o k
*/
type GetSettingsGroupOK struct {
}

func (o *GetSettingsGroupOK) Error() string {
	return fmt.Sprintf("[GET /{groupId}][%d] getSettingsGroupOK ", 200)
}

func (o *GetSettingsGroupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
