package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetDatetimeFormatPatternReader is a Reader for the GetDatetimeFormatPattern structure.
type GetDatetimeFormatPatternReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetDatetimeFormatPatternReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDatetimeFormatPatternOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDatetimeFormatPatternOK creates a GetDatetimeFormatPatternOK with default headers values
func NewGetDatetimeFormatPatternOK() *GetDatetimeFormatPatternOK {
	return &GetDatetimeFormatPatternOK{}
}

/*GetDatetimeFormatPatternOK handles this case with default header values.

GetDatetimeFormatPatternOK get datetime format pattern o k
*/
type GetDatetimeFormatPatternOK struct {
}

func (o *GetDatetimeFormatPatternOK) Error() string {
	return fmt.Sprintf("[GET /datetimeFormatPattern][%d] getDatetimeFormatPatternOK ", 200)
}

func (o *GetDatetimeFormatPatternOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
