package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetSettingsGroupParams creates a new GetSettingsGroupParams object
// with the default values initialized.
func NewGetSettingsGroupParams() *GetSettingsGroupParams {
	var ()
	return &GetSettingsGroupParams{}
}

/*GetSettingsGroupParams contains all the parameters to send to the API endpoint
for the get settings group operation typically these are written to a http.Request
*/
type GetSettingsGroupParams struct {

	/*GroupID*/
	GroupID *string
}

// WithGroupID adds the groupId to the get settings group params
func (o *GetSettingsGroupParams) WithGroupID(groupId *string) *GetSettingsGroupParams {
	o.GroupID = groupId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSettingsGroupParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.GroupID != nil {

		// path param groupId
		if err := r.SetPathParam("groupId", *o.GroupID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
