package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetAttributesReader is a Reader for the GetAttributes structure.
type GetAttributesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetAttributesReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAttributesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAttributesOK creates a GetAttributesOK with default headers values
func NewGetAttributesOK() *GetAttributesOK {
	return &GetAttributesOK{}
}

/*GetAttributesOK handles this case with default header values.

GetAttributesOK get attributes o k
*/
type GetAttributesOK struct {
}

func (o *GetAttributesOK) Error() string {
	return fmt.Sprintf("[GET /attributes][%d] getAttributesOK ", 200)
}

func (o *GetAttributesOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
