package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetDiscoverReader is a Reader for the GetDiscover structure.
type GetDiscoverReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetDiscoverReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDiscoverOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDiscoverOK creates a GetDiscoverOK with default headers values
func NewGetDiscoverOK() *GetDiscoverOK {
	return &GetDiscoverOK{}
}

/*GetDiscoverOK handles this case with default header values.

GetDiscoverOK get discover o k
*/
type GetDiscoverOK struct {
}

func (o *GetDiscoverOK) Error() string {
	return fmt.Sprintf("[GET /{uri: .+}][%d] getDiscoverOK ", 200)
}

func (o *GetDiscoverOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
