package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetSpecificAttributeReader is a Reader for the GetSpecificAttribute structure.
type GetSpecificAttributeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetSpecificAttributeReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSpecificAttributeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSpecificAttributeOK creates a GetSpecificAttributeOK with default headers values
func NewGetSpecificAttributeOK() *GetSpecificAttributeOK {
	return &GetSpecificAttributeOK{}
}

/*GetSpecificAttributeOK handles this case with default header values.

GetSpecificAttributeOK get specific attribute o k
*/
type GetSpecificAttributeOK struct {
}

func (o *GetSpecificAttributeOK) Error() string {
	return fmt.Sprintf("[GET /{attrName}][%d] getSpecificAttributeOK ", 200)
}

func (o *GetSpecificAttributeOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
