package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetInputControlsInitialValuesParams creates a new GetInputControlsInitialValuesParams object
// with the default values initialized.
func NewGetInputControlsInitialValuesParams() *GetInputControlsInitialValuesParams {
	var (
		freshDataDefault bool = bool(false)
	)
	return &GetInputControlsInitialValuesParams{
		FreshData: &freshDataDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInputControlsInitialValuesParamsWithTimeout creates a new GetInputControlsInitialValuesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInputControlsInitialValuesParamsWithTimeout(timeout time.Duration) *GetInputControlsInitialValuesParams {
	var (
		freshDataDefault bool = bool(false)
	)
	return &GetInputControlsInitialValuesParams{
		FreshData: &freshDataDefault,

		timeout: timeout,
	}
}

/*GetInputControlsInitialValuesParams contains all the parameters to send to the API endpoint
for the get input controls initial values operation typically these are written to a http.Request
*/
type GetInputControlsInitialValuesParams struct {

	/*FreshData*/
	FreshData *bool
	/*ReportUnitURI*/
	ReportUnitURI *string

	timeout time.Duration
}

// WithFreshData adds the freshData to the get input controls initial values params
func (o *GetInputControlsInitialValuesParams) WithFreshData(FreshData *bool) *GetInputControlsInitialValuesParams {
	o.FreshData = FreshData
	return o
}

// WithReportUnitURI adds the reportUnitUri to the get input controls initial values params
func (o *GetInputControlsInitialValuesParams) WithReportUnitURI(ReportUnitURI *string) *GetInputControlsInitialValuesParams {
	o.ReportUnitURI = ReportUnitURI
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetInputControlsInitialValuesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.FreshData != nil {

		// query param freshData
		var qrFreshData bool
		if o.FreshData != nil {
			qrFreshData = *o.FreshData
		}
		qFreshData := swag.FormatBool(qrFreshData)
		if qFreshData != "" {
			if err := r.SetQueryParam("freshData", qFreshData); err != nil {
				return err
			}
		}

	}

	if o.ReportUnitURI != nil {

		// query param reportUnitURI
		var qrReportUnitURI string
		if o.ReportUnitURI != nil {
			qrReportUnitURI = *o.ReportUnitURI
		}
		qReportUnitURI := qrReportUnitURI
		if qReportUnitURI != "" {
			if err := r.SetQueryParam("reportUnitURI", qReportUnitURI); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
