package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAttachmentParams creates a new GetAttachmentParams object
// with the default values initialized.
func NewGetAttachmentParams() *GetAttachmentParams {
	var ()
	return &GetAttachmentParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAttachmentParamsWithTimeout creates a new GetAttachmentParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAttachmentParamsWithTimeout(timeout time.Duration) *GetAttachmentParams {
	var ()
	return &GetAttachmentParams{

		timeout: timeout,
	}
}

/*GetAttachmentParams contains all the parameters to send to the API endpoint
for the get attachment operation typically these are written to a http.Request
*/
type GetAttachmentParams struct {

	/*Attachment*/
	Attachment *string
	/*ExecutionID*/
	ExecutionID *string
	/*ExportID*/
	ExportID *string

	timeout time.Duration
}

// WithAttachment adds the attachment to the get attachment params
func (o *GetAttachmentParams) WithAttachment(Attachment *string) *GetAttachmentParams {
	o.Attachment = Attachment
	return o
}

// WithExecutionID adds the executionId to the get attachment params
func (o *GetAttachmentParams) WithExecutionID(ExecutionID *string) *GetAttachmentParams {
	o.ExecutionID = ExecutionID
	return o
}

// WithExportID adds the exportId to the get attachment params
func (o *GetAttachmentParams) WithExportID(ExportID *string) *GetAttachmentParams {
	o.ExportID = ExportID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetAttachmentParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Attachment != nil {

		// path param attachment
		if err := r.SetPathParam("attachment", *o.Attachment); err != nil {
			return err
		}

	}

	if o.ExecutionID != nil {

		// path param executionId
		if err := r.SetPathParam("executionId", *o.ExecutionID); err != nil {
			return err
		}

	}

	if o.ExportID != nil {

		// path param exportId
		if err := r.SetPathParam("exportId", *o.ExportID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
