package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSettingsGroupParams creates a new GetSettingsGroupParams object
// with the default values initialized.
func NewGetSettingsGroupParams() *GetSettingsGroupParams {
	var ()
	return &GetSettingsGroupParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSettingsGroupParamsWithTimeout creates a new GetSettingsGroupParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSettingsGroupParamsWithTimeout(timeout time.Duration) *GetSettingsGroupParams {
	var ()
	return &GetSettingsGroupParams{

		timeout: timeout,
	}
}

/*GetSettingsGroupParams contains all the parameters to send to the API endpoint
for the get settings group operation typically these are written to a http.Request
*/
type GetSettingsGroupParams struct {

	/*GroupID*/
	GroupID *string

	timeout time.Duration
}

// WithGroupID adds the groupId to the get settings group params
func (o *GetSettingsGroupParams) WithGroupID(GroupID *string) *GetSettingsGroupParams {
	o.GroupID = GroupID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSettingsGroupParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.GroupID != nil {

		// path param groupId
		if err := r.SetPathParam("groupId", *o.GroupID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
