package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetReportExecutionStatusObjectReader is a Reader for the GetReportExecutionStatusObject structure.
type GetReportExecutionStatusObjectReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetReportExecutionStatusObjectReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetReportExecutionStatusObjectOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetReportExecutionStatusObjectOK creates a GetReportExecutionStatusObjectOK with default headers values
func NewGetReportExecutionStatusObjectOK() *GetReportExecutionStatusObjectOK {
	return &GetReportExecutionStatusObjectOK{}
}

/*GetReportExecutionStatusObjectOK handles this case with default header values.

GetReportExecutionStatusObjectOK get report execution status object o k
*/
type GetReportExecutionStatusObjectOK struct {
}

func (o *GetReportExecutionStatusObjectOK) Error() string {
	return fmt.Sprintf("[GET /{executionId}/status][%d] getReportExecutionStatusObjectOK ", 200)
}

func (o *GetReportExecutionStatusObjectOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
