package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetReportInputParametersReader is a Reader for the GetReportInputParameters structure.
type GetReportInputParametersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetReportInputParametersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetReportInputParametersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetReportInputParametersOK creates a GetReportInputParametersOK with default headers values
func NewGetReportInputParametersOK() *GetReportInputParametersOK {
	return &GetReportInputParametersOK{}
}

/*GetReportInputParametersOK handles this case with default header values.

GetReportInputParametersOK get report input parameters o k
*/
type GetReportInputParametersOK struct {
}

func (o *GetReportInputParametersOK) Error() string {
	return fmt.Sprintf("[GET /reports/{reportUnitURI: .+}/inputControls][%d] getReportInputParametersOK ", 200)
}

func (o *GetReportInputParametersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
