package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetDownloadFileReader is a Reader for the GetDownloadFile structure.
type GetDownloadFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetDownloadFileReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDownloadFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDownloadFileOK creates a GetDownloadFileOK with default headers values
func NewGetDownloadFileOK() *GetDownloadFileOK {
	return &GetDownloadFileOK{}
}

/*GetDownloadFileOK handles this case with default header values.

GetDownloadFileOK get download file o k
*/
type GetDownloadFileOK struct {
}

func (o *GetDownloadFileOK) Error() string {
	return fmt.Sprintf("[GET /{id}/{name}][%d] getDownloadFileOK ", 200)
}

func (o *GetDownloadFileOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
