package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetDownloadFileParams creates a new GetDownloadFileParams object
// with the default values initialized.
func NewGetDownloadFileParams() *GetDownloadFileParams {
	var ()
	return &GetDownloadFileParams{}
}

/*GetDownloadFileParams contains all the parameters to send to the API endpoint
for the get download file operation typically these are written to a http.Request
*/
type GetDownloadFileParams struct {

	/*ID*/
	ID *string
	/*Name*/
	Name *string
}

// WithID adds the id to the get download file params
func (o *GetDownloadFileParams) WithID(id *string) *GetDownloadFileParams {
	o.ID = id
	return o
}

// WithName adds the name to the get download file params
func (o *GetDownloadFileParams) WithName(name *string) *GetDownloadFileParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetDownloadFileParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.ID != nil {

		// path param id
		if err := r.SetPathParam("id", *o.ID); err != nil {
			return err
		}

	}

	if o.Name != nil {

		// path param name
		if err := r.SetPathParam("name", *o.Name); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
