package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetReportExecutionStatusObjectParams creates a new GetReportExecutionStatusObjectParams object
// with the default values initialized.
func NewGetReportExecutionStatusObjectParams() *GetReportExecutionStatusObjectParams {
	var ()
	return &GetReportExecutionStatusObjectParams{}
}

/*GetReportExecutionStatusObjectParams contains all the parameters to send to the API endpoint
for the get report execution status object operation typically these are written to a http.Request
*/
type GetReportExecutionStatusObjectParams struct {

	/*ExecutionID*/
	ExecutionID *string
}

// WithExecutionID adds the executionId to the get report execution status object params
func (o *GetReportExecutionStatusObjectParams) WithExecutionID(executionId *string) *GetReportExecutionStatusObjectParams {
	o.ExecutionID = executionId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetReportExecutionStatusObjectParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.ExecutionID != nil {

		// path param executionId
		if err := r.SetPathParam("executionId", *o.ExecutionID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
