package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetAttributesOfUserReader is a Reader for the GetAttributesOfUser structure.
type GetAttributesOfUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetAttributesOfUserReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAttributesOfUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetAttributesOfUserOK creates a GetAttributesOfUserOK with default headers values
func NewGetAttributesOfUserOK() *GetAttributesOfUserOK {
	return &GetAttributesOfUserOK{}
}

/*GetAttributesOfUserOK handles this case with default header values.

GetAttributesOfUserOK get attributes of user o k
*/
type GetAttributesOfUserOK struct {
}

func (o *GetAttributesOfUserOK) Error() string {
	return fmt.Sprintf("[GET /{name}/attributes][%d] getAttributesOfUserOK ", 200)
}

func (o *GetAttributesOfUserOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
