package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetCalendarNamesReader is a Reader for the GetCalendarNames structure.
type GetCalendarNamesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetCalendarNamesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetCalendarNamesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetCalendarNamesOK creates a GetCalendarNamesOK with default headers values
func NewGetCalendarNamesOK() *GetCalendarNamesOK {
	return &GetCalendarNamesOK{}
}

/*GetCalendarNamesOK handles this case with default header values.

GetCalendarNamesOK get calendar names o k
*/
type GetCalendarNamesOK struct {
}

func (o *GetCalendarNamesOK) Error() string {
	return fmt.Sprintf("[GET /calendars][%d] getCalendarNamesOK ", 200)
}

func (o *GetCalendarNamesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
