package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetServerEditionReader is a Reader for the GetServerEdition structure.
type GetServerEditionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetServerEditionReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetServerEditionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetServerEditionOK creates a GetServerEditionOK with default headers values
func NewGetServerEditionOK() *GetServerEditionOK {
	return &GetServerEditionOK{}
}

/*GetServerEditionOK handles this case with default header values.

GetServerEditionOK get server edition o k
*/
type GetServerEditionOK struct {
}

func (o *GetServerEditionOK) Error() string {
	return fmt.Sprintf("[GET /edition][%d] getServerEditionOK ", 200)
}

func (o *GetServerEditionOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
