package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// GetConnectionDetailsReader is a Reader for the GetConnectionDetails structure.
type GetConnectionDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetConnectionDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetConnectionDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetConnectionDetailsOK creates a GetConnectionDetailsOK with default headers values
func NewGetConnectionDetailsOK() *GetConnectionDetailsOK {
	return &GetConnectionDetailsOK{}
}

/*GetConnectionDetailsOK handles this case with default header values.

GetConnectionDetailsOK get connection details o k
*/
type GetConnectionDetailsOK struct {
}

func (o *GetConnectionDetailsOK) Error() string {
	return fmt.Sprintf("[GET /{uuid}][%d] getConnectionDetailsOK ", 200)
}

func (o *GetConnectionDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
