package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetUsersParams creates a new GetUsersParams object
// with the default values initialized.
func NewGetUsersParams() *GetUsersParams {
	var ()
	return &GetUsersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUsersParamsWithTimeout creates a new GetUsersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUsersParamsWithTimeout(timeout time.Duration) *GetUsersParams {
	var ()
	return &GetUsersParams{

		timeout: timeout,
	}
}

/*GetUsersParams contains all the parameters to send to the API endpoint
for the get users operation typically these are written to a http.Request
*/
type GetUsersParams struct {

	/*HasAllRequiredRoles*/
	HasAllRequiredRoles *bool
	/*IncludeSubOrgs*/
	IncludeSubOrgs *bool
	/*Limit*/
	Limit *int32
	/*MaxRecords*/
	MaxRecords *int32
	/*Offset*/
	Offset *int32
	/*Q*/
	Q *string
	/*RequiredRole*/
	RequiredRole *string
	/*Search*/
	Search *string
	/*SubOrgID*/
	SubOrgID *string

	timeout time.Duration
}

// WithHasAllRequiredRoles adds the hasAllRequiredRoles to the get users params
func (o *GetUsersParams) WithHasAllRequiredRoles(HasAllRequiredRoles *bool) *GetUsersParams {
	o.HasAllRequiredRoles = HasAllRequiredRoles
	return o
}

// WithIncludeSubOrgs adds the includeSubOrgs to the get users params
func (o *GetUsersParams) WithIncludeSubOrgs(IncludeSubOrgs *bool) *GetUsersParams {
	o.IncludeSubOrgs = IncludeSubOrgs
	return o
}

// WithLimit adds the limit to the get users params
func (o *GetUsersParams) WithLimit(Limit *int32) *GetUsersParams {
	o.Limit = Limit
	return o
}

// WithMaxRecords adds the maxRecords to the get users params
func (o *GetUsersParams) WithMaxRecords(MaxRecords *int32) *GetUsersParams {
	o.MaxRecords = MaxRecords
	return o
}

// WithOffset adds the offset to the get users params
func (o *GetUsersParams) WithOffset(Offset *int32) *GetUsersParams {
	o.Offset = Offset
	return o
}

// WithQ adds the q to the get users params
func (o *GetUsersParams) WithQ(Q *string) *GetUsersParams {
	o.Q = Q
	return o
}

// WithRequiredRole adds the requiredRole to the get users params
func (o *GetUsersParams) WithRequiredRole(RequiredRole *string) *GetUsersParams {
	o.RequiredRole = RequiredRole
	return o
}

// WithSearch adds the search to the get users params
func (o *GetUsersParams) WithSearch(Search *string) *GetUsersParams {
	o.Search = Search
	return o
}

// WithSubOrgID adds the subOrgId to the get users params
func (o *GetUsersParams) WithSubOrgID(SubOrgID *string) *GetUsersParams {
	o.SubOrgID = SubOrgID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.HasAllRequiredRoles != nil {

		// query param hasAllRequiredRoles
		var qrHasAllRequiredRoles bool
		if o.HasAllRequiredRoles != nil {
			qrHasAllRequiredRoles = *o.HasAllRequiredRoles
		}
		qHasAllRequiredRoles := swag.FormatBool(qrHasAllRequiredRoles)
		if qHasAllRequiredRoles != "" {
			if err := r.SetQueryParam("hasAllRequiredRoles", qHasAllRequiredRoles); err != nil {
				return err
			}
		}

	}

	if o.IncludeSubOrgs != nil {

		// query param includeSubOrgs
		var qrIncludeSubOrgs bool
		if o.IncludeSubOrgs != nil {
			qrIncludeSubOrgs = *o.IncludeSubOrgs
		}
		qIncludeSubOrgs := swag.FormatBool(qrIncludeSubOrgs)
		if qIncludeSubOrgs != "" {
			if err := r.SetQueryParam("includeSubOrgs", qIncludeSubOrgs); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.MaxRecords != nil {

		// query param maxRecords
		var qrMaxRecords int32
		if o.MaxRecords != nil {
			qrMaxRecords = *o.MaxRecords
		}
		qMaxRecords := swag.FormatInt32(qrMaxRecords)
		if qMaxRecords != "" {
			if err := r.SetQueryParam("maxRecords", qMaxRecords); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int32
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt32(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if o.Q != nil {

		// query param q
		var qrQ string
		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {
			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}

	}

	if o.RequiredRole != nil {

		// query param requiredRole
		var qrRequiredRole string
		if o.RequiredRole != nil {
			qrRequiredRole = *o.RequiredRole
		}
		qRequiredRole := qrRequiredRole
		if qRequiredRole != "" {
			if err := r.SetQueryParam("requiredRole", qRequiredRole); err != nil {
				return err
			}
		}

	}

	if o.Search != nil {

		// query param search
		var qrSearch string
		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {
			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}

	}

	if o.SubOrgID != nil {

		// query param subOrgId
		var qrSubOrgID string
		if o.SubOrgID != nil {
			qrSubOrgID = *o.SubOrgID
		}
		qSubOrgID := qrSubOrgID
		if qSubOrgID != "" {
			if err := r.SetQueryParam("subOrgId", qSubOrgID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
