package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetReportInputParametersForSpecifiedInputControlsParams creates a new GetReportInputParametersForSpecifiedInputControlsParams object
// with the default values initialized.
func NewGetReportInputParametersForSpecifiedInputControlsParams() *GetReportInputParametersForSpecifiedInputControlsParams {
	var ()
	return &GetReportInputParametersForSpecifiedInputControlsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReportInputParametersForSpecifiedInputControlsParamsWithTimeout creates a new GetReportInputParametersForSpecifiedInputControlsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReportInputParametersForSpecifiedInputControlsParamsWithTimeout(timeout time.Duration) *GetReportInputParametersForSpecifiedInputControlsParams {
	var ()
	return &GetReportInputParametersForSpecifiedInputControlsParams{

		timeout: timeout,
	}
}

/*GetReportInputParametersForSpecifiedInputControlsParams contains all the parameters to send to the API endpoint
for the get report input parameters for specified input controls operation typically these are written to a http.Request
*/
type GetReportInputParametersForSpecifiedInputControlsParams struct {

	/*InputControlIds*/
	InputControlIds *string
	/*ReportUnitURI*/
	ReportUnitURI *string

	timeout time.Duration
}

// WithInputControlIds adds the inputControlIds to the get report input parameters for specified input controls params
func (o *GetReportInputParametersForSpecifiedInputControlsParams) WithInputControlIds(InputControlIds *string) *GetReportInputParametersForSpecifiedInputControlsParams {
	o.InputControlIds = InputControlIds
	return o
}

// WithReportUnitURI adds the reportUnitUri to the get report input parameters for specified input controls params
func (o *GetReportInputParametersForSpecifiedInputControlsParams) WithReportUnitURI(ReportUnitURI *string) *GetReportInputParametersForSpecifiedInputControlsParams {
	o.ReportUnitURI = ReportUnitURI
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetReportInputParametersForSpecifiedInputControlsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.InputControlIds != nil {

		// query param inputControlIds
		var qrInputControlIds string
		if o.InputControlIds != nil {
			qrInputControlIds = *o.InputControlIds
		}
		qInputControlIds := qrInputControlIds
		if qInputControlIds != "" {
			if err := r.SetQueryParam("inputControlIds", qInputControlIds); err != nil {
				return err
			}
		}

	}

	if o.ReportUnitURI != nil {

		// query param reportUnitURI
		var qrReportUnitURI string
		if o.ReportUnitURI != nil {
			qrReportUnitURI = *o.ReportUnitURI
		}
		qReportUnitURI := qrReportUnitURI
		if qReportUnitURI != "" {
			if err := r.SetQueryParam("reportUnitURI", qReportUnitURI); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
