package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetPermissionsEntryPointRootParams creates a new GetPermissionsEntryPointRootParams object
// with the default values initialized.
func NewGetPermissionsEntryPointRootParams() *GetPermissionsEntryPointRootParams {

	return &GetPermissionsEntryPointRootParams{}
}

/*GetPermissionsEntryPointRootParams contains all the parameters to send to the API endpoint
for the get permissions entry point root operation typically these are written to a http.Request
*/
type GetPermissionsEntryPointRootParams struct {
}

// WriteToRequest writes these params to a swagger request
func (o *GetPermissionsEntryPointRootParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
