package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetDateFormatPatternReader is a Reader for the GetDateFormatPattern structure.
type GetDateFormatPatternReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetDateFormatPatternReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDateFormatPatternOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDateFormatPatternOK creates a GetDateFormatPatternOK with default headers values
func NewGetDateFormatPatternOK() *GetDateFormatPatternOK {
	return &GetDateFormatPatternOK{}
}

/*GetDateFormatPatternOK handles this case with default header values.

GetDateFormatPatternOK get date format pattern o k
*/
type GetDateFormatPatternOK struct {
}

func (o *GetDateFormatPatternOK) Error() string {
	return fmt.Sprintf("[GET /dateFormatPattern][%d] getDateFormatPatternOK ", 200)
}

func (o *GetDateFormatPatternOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
