package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServerExpirationParams creates a new GetServerExpirationParams object
// with the default values initialized.
func NewGetServerExpirationParams() *GetServerExpirationParams {

	return &GetServerExpirationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServerExpirationParamsWithTimeout creates a new GetServerExpirationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServerExpirationParamsWithTimeout(timeout time.Duration) *GetServerExpirationParams {

	return &GetServerExpirationParams{

		timeout: timeout,
	}
}

/*GetServerExpirationParams contains all the parameters to send to the API endpoint
for the get server expiration operation typically these are written to a http.Request
*/
type GetServerExpirationParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *GetServerExpirationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
