package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDateFormatPatternParams creates a new GetDateFormatPatternParams object
// with the default values initialized.
func NewGetDateFormatPatternParams() *GetDateFormatPatternParams {

	return &GetDateFormatPatternParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDateFormatPatternParamsWithTimeout creates a new GetDateFormatPatternParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDateFormatPatternParamsWithTimeout(timeout time.Duration) *GetDateFormatPatternParams {

	return &GetDateFormatPatternParams{

		timeout: timeout,
	}
}

/*GetDateFormatPatternParams contains all the parameters to send to the API endpoint
for the get date format pattern operation typically these are written to a http.Request
*/
type GetDateFormatPatternParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *GetDateFormatPatternParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
