package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// GetTasksIdsReader is a Reader for the GetTasksIds structure.
type GetTasksIdsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetTasksIdsReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetTasksIdsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTasksIdsOK creates a GetTasksIdsOK with default headers values
func NewGetTasksIdsOK() *GetTasksIdsOK {
	return &GetTasksIdsOK{}
}

/*GetTasksIdsOK handles this case with default header values.

GetTasksIdsOK get tasks ids o k
*/
type GetTasksIdsOK struct {
}

func (o *GetTasksIdsOK) Error() string {
	return fmt.Sprintf("[GET /import][%d] getTasksIdsOK ", 200)
}

func (o *GetTasksIdsOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
