package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetConnectionDetailsParams creates a new GetConnectionDetailsParams object
// with the default values initialized.
func NewGetConnectionDetailsParams() *GetConnectionDetailsParams {
	var ()
	return &GetConnectionDetailsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetConnectionDetailsParamsWithTimeout creates a new GetConnectionDetailsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetConnectionDetailsParamsWithTimeout(timeout time.Duration) *GetConnectionDetailsParams {
	var ()
	return &GetConnectionDetailsParams{

		timeout: timeout,
	}
}

/*GetConnectionDetailsParams contains all the parameters to send to the API endpoint
for the get connection details operation typically these are written to a http.Request
*/
type GetConnectionDetailsParams struct {

	/*UUID*/
	UUID *string

	timeout time.Duration
}

// WithUUID adds the uuid to the get connection details params
func (o *GetConnectionDetailsParams) WithUUID(UUID *string) *GetConnectionDetailsParams {
	o.UUID = UUID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetConnectionDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.UUID != nil {

		// path param uuid
		if err := r.SetPathParam("uuid", *o.UUID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
