package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetCustomDataSourceDefinitionParams creates a new GetCustomDataSourceDefinitionParams object
// with the default values initialized.
func NewGetCustomDataSourceDefinitionParams() *GetCustomDataSourceDefinitionParams {
	var ()
	return &GetCustomDataSourceDefinitionParams{}
}

/*GetCustomDataSourceDefinitionParams contains all the parameters to send to the API endpoint
for the get custom data source definition operation typically these are written to a http.Request
*/
type GetCustomDataSourceDefinitionParams struct {

	/*Name*/
	Name *string
}

// WithName adds the name to the get custom data source definition params
func (o *GetCustomDataSourceDefinitionParams) WithName(name *string) *GetCustomDataSourceDefinitionParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetCustomDataSourceDefinitionParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Name != nil {

		// path param name
		if err := r.SetPathParam("name", *o.Name); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
