package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetReportInputControlValuesParams creates a new GetReportInputControlValuesParams object
// with the default values initialized.
func NewGetReportInputControlValuesParams() *GetReportInputControlValuesParams {
	var (
		freshDataDefault bool = bool(false)
	)
	return &GetReportInputControlValuesParams{
		FreshData: &freshDataDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetReportInputControlValuesParamsWithTimeout creates a new GetReportInputControlValuesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetReportInputControlValuesParamsWithTimeout(timeout time.Duration) *GetReportInputControlValuesParams {
	var (
		freshDataDefault bool = bool(false)
	)
	return &GetReportInputControlValuesParams{
		FreshData: &freshDataDefault,

		timeout: timeout,
	}
}

/*GetReportInputControlValuesParams contains all the parameters to send to the API endpoint
for the get report input control values operation typically these are written to a http.Request
*/
type GetReportInputControlValuesParams struct {

	/*FreshData*/
	FreshData *bool
	/*InputControlIds*/
	InputControlIds *string
	/*ReportUnitURI*/
	ReportUnitURI *string

	timeout time.Duration
}

// WithFreshData adds the freshData to the get report input control values params
func (o *GetReportInputControlValuesParams) WithFreshData(FreshData *bool) *GetReportInputControlValuesParams {
	o.FreshData = FreshData
	return o
}

// WithInputControlIds adds the inputControlIds to the get report input control values params
func (o *GetReportInputControlValuesParams) WithInputControlIds(InputControlIds *string) *GetReportInputControlValuesParams {
	o.InputControlIds = InputControlIds
	return o
}

// WithReportUnitURI adds the reportUnitUri to the get report input control values params
func (o *GetReportInputControlValuesParams) WithReportUnitURI(ReportUnitURI *string) *GetReportInputControlValuesParams {
	o.ReportUnitURI = ReportUnitURI
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetReportInputControlValuesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.FreshData != nil {

		// query param freshData
		var qrFreshData bool
		if o.FreshData != nil {
			qrFreshData = *o.FreshData
		}
		qFreshData := swag.FormatBool(qrFreshData)
		if qFreshData != "" {
			if err := r.SetQueryParam("freshData", qFreshData); err != nil {
				return err
			}
		}

	}

	if o.InputControlIds != nil {

		// query param inputControlIds
		var qrInputControlIds string
		if o.InputControlIds != nil {
			qrInputControlIds = *o.InputControlIds
		}
		qInputControlIds := qrInputControlIds
		if qInputControlIds != "" {
			if err := r.SetQueryParam("inputControlIds", qInputControlIds); err != nil {
				return err
			}
		}

	}

	if o.ReportUnitURI != nil {

		// query param reportUnitURI
		var qrReportUnitURI string
		if o.ReportUnitURI != nil {
			qrReportUnitURI = *o.ReportUnitURI
		}
		qReportUnitURI := qrReportUnitURI
		if qReportUnitURI != "" {
			if err := r.SetQueryParam("reportUnitURI", qReportUnitURI); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
