package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ModifyConnectionReader is a Reader for the ModifyConnection structure.
type ModifyConnectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *ModifyConnectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewModifyConnectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewModifyConnectionOK creates a ModifyConnectionOK with default headers values
func NewModifyConnectionOK() *ModifyConnectionOK {
	return &ModifyConnectionOK{}
}

/*ModifyConnectionOK handles this case with default header values.

ModifyConnectionOK modify connection o k
*/
type ModifyConnectionOK struct {
}

func (o *ModifyConnectionOK) Error() string {
	return fmt.Sprintf("[PUT /{uuid}][%d] modifyConnectionOK ", 200)
}

func (o *ModifyConnectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
