package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewModifyConnectionParams creates a new ModifyConnectionParams object
// with the default values initialized.
func NewModifyConnectionParams() *ModifyConnectionParams {
	var ()
	return &ModifyConnectionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewModifyConnectionParamsWithTimeout creates a new ModifyConnectionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewModifyConnectionParamsWithTimeout(timeout time.Duration) *ModifyConnectionParams {
	var ()
	return &ModifyConnectionParams{

		timeout: timeout,
	}
}

/*ModifyConnectionParams contains all the parameters to send to the API endpoint
for the modify connection operation typically these are written to a http.Request
*/
type ModifyConnectionParams struct {

	/*ContentType*/
	ContentType *string
	/*UUID*/
	UUID *string

	timeout time.Duration
}

// WithContentType adds the contentType to the modify connection params
func (o *ModifyConnectionParams) WithContentType(ContentType *string) *ModifyConnectionParams {
	o.ContentType = ContentType
	return o
}

// WithUUID adds the uuid to the modify connection params
func (o *ModifyConnectionParams) WithUUID(UUID *string) *ModifyConnectionParams {
	o.UUID = UUID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyConnectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.ContentType != nil {

		// query param Content-Type
		var qrContentType string
		if o.ContentType != nil {
			qrContentType = *o.ContentType
		}
		qContentType := qrContentType
		if qContentType != "" {
			if err := r.SetQueryParam("Content-Type", qContentType); err != nil {
				return err
			}
		}

	}

	if o.UUID != nil {

		// path param uuid
		if err := r.SetPathParam("uuid", *o.UUID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
