package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PatchResourceReader is a Reader for the PatchResource structure.
type PatchResourceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PatchResourceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPatchResourceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPatchResourceOK creates a PatchResourceOK with default headers values
func NewPatchResourceOK() *PatchResourceOK {
	return &PatchResourceOK{}
}

/*PatchResourceOK handles this case with default header values.

PatchResourceOK patch resource o k
*/
type PatchResourceOK struct {
}

func (o *PatchResourceOK) Error() string {
	return fmt.Sprintf("[PATCH /{uri: .+}][%d] patchResourceOK ", 200)
}

func (o *PatchResourceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
