package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PostReportsReportUnitURIInputControlsReader is a Reader for the PostReportsReportUnitURIInputControls structure.
type PostReportsReportUnitURIInputControlsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PostReportsReportUnitURIInputControlsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostReportsReportUnitURIInputControlsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostReportsReportUnitURIInputControlsOK creates a PostReportsReportUnitURIInputControlsOK with default headers values
func NewPostReportsReportUnitURIInputControlsOK() *PostReportsReportUnitURIInputControlsOK {
	return &PostReportsReportUnitURIInputControlsOK{}
}

/*PostReportsReportUnitURIInputControlsOK handles this case with default header values.

PostReportsReportUnitURIInputControlsOK post reports report unit Uri input controls o k
*/
type PostReportsReportUnitURIInputControlsOK struct {
}

func (o *PostReportsReportUnitURIInputControlsOK) Error() string {
	return fmt.Sprintf("[POST /reports/{reportUnitURI: .+}/inputControls][%d] postReportsReportUnitUriInputControlsOK ", 200)
}

func (o *PostReportsReportUnitURIInputControlsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
