package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutAttributesReader is a Reader for the PutAttributes structure.
type PutAttributesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PutAttributesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutAttributesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAttributesOK creates a PutAttributesOK with default headers values
func NewPutAttributesOK() *PutAttributesOK {
	return &PutAttributesOK{}
}

/*PutAttributesOK handles this case with default header values.

PutAttributesOK put attributes o k
*/
type PutAttributesOK struct {
}

func (o *PutAttributesOK) Error() string {
	return fmt.Sprintf("[PUT /attributes][%d] putAttributesOK ", 200)
}

func (o *PutAttributesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
