package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PutAttributeReader is a Reader for the PutAttribute structure.
type PutAttributeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *PutAttributeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPutAttributeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPutAttributeOK creates a PutAttributeOK with default headers values
func NewPutAttributeOK() *PutAttributeOK {
	return &PutAttributeOK{}
}

/*PutAttributeOK handles this case with default header values.

PutAttributeOK put attribute o k
*/
type PutAttributeOK struct {
}

func (o *PutAttributeOK) Error() string {
	return fmt.Sprintf("[PUT /{attrName}][%d] putAttributeOK ", 200)
}

func (o *PutAttributeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
