package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPutNameAttributesAttrNameParams creates a new PutNameAttributesAttrNameParams object
// with the default values initialized.
func NewPutNameAttributesAttrNameParams() *PutNameAttributesAttrNameParams {
	var ()
	return &PutNameAttributesAttrNameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutNameAttributesAttrNameParamsWithTimeout creates a new PutNameAttributesAttrNameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutNameAttributesAttrNameParamsWithTimeout(timeout time.Duration) *PutNameAttributesAttrNameParams {
	var ()
	return &PutNameAttributesAttrNameParams{

		timeout: timeout,
	}
}

/*PutNameAttributesAttrNameParams contains all the parameters to send to the API endpoint
for the put name attributes attr name operation typically these are written to a http.Request
*/
type PutNameAttributesAttrNameParams struct {

	/*Accept*/
	Accept *string
	/*ContentType*/
	ContentType *string
	/*Embedded*/
	Embedded *string
	/*AttrName*/
	AttrName *string
	/*Name*/
	Name *string

	timeout time.Duration
}

// WithAccept adds the accept to the put name attributes attr name params
func (o *PutNameAttributesAttrNameParams) WithAccept(Accept *string) *PutNameAttributesAttrNameParams {
	o.Accept = Accept
	return o
}

// WithContentType adds the contentType to the put name attributes attr name params
func (o *PutNameAttributesAttrNameParams) WithContentType(ContentType *string) *PutNameAttributesAttrNameParams {
	o.ContentType = ContentType
	return o
}

// WithEmbedded adds the embedded to the put name attributes attr name params
func (o *PutNameAttributesAttrNameParams) WithEmbedded(Embedded *string) *PutNameAttributesAttrNameParams {
	o.Embedded = Embedded
	return o
}

// WithAttrName adds the attrName to the put name attributes attr name params
func (o *PutNameAttributesAttrNameParams) WithAttrName(AttrName *string) *PutNameAttributesAttrNameParams {
	o.AttrName = AttrName
	return o
}

// WithName adds the name to the put name attributes attr name params
func (o *PutNameAttributesAttrNameParams) WithName(Name *string) *PutNameAttributesAttrNameParams {
	o.Name = Name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PutNameAttributesAttrNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Accept != nil {

		// query param Accept
		var qrAccept string
		if o.Accept != nil {
			qrAccept = *o.Accept
		}
		qAccept := qrAccept
		if qAccept != "" {
			if err := r.SetQueryParam("Accept", qAccept); err != nil {
				return err
			}
		}

	}

	if o.ContentType != nil {

		// query param Content-Type
		var qrContentType string
		if o.ContentType != nil {
			qrContentType = *o.ContentType
		}
		qContentType := qrContentType
		if qContentType != "" {
			if err := r.SetQueryParam("Content-Type", qContentType); err != nil {
				return err
			}
		}

	}

	if o.Embedded != nil {

		// query param _embedded
		var qrEmbedded string
		if o.Embedded != nil {
			qrEmbedded = *o.Embedded
		}
		qEmbedded := qrEmbedded
		if qEmbedded != "" {
			if err := r.SetQueryParam("_embedded", qEmbedded); err != nil {
				return err
			}
		}

	}

	if o.AttrName != nil {

		// path param attrName
		if err := r.SetPathParam("attrName", *o.AttrName); err != nil {
			return err
		}

	}

	if o.Name != nil {

		// path param name
		if err := r.SetPathParam("name", *o.Name); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
