package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewPutAttributesParams creates a new PutAttributesParams object
// with the default values initialized.
func NewPutAttributesParams() *PutAttributesParams {
	var ()
	return &PutAttributesParams{}
}

/*PutAttributesParams contains all the parameters to send to the API endpoint
for the put attributes operation typically these are written to a http.Request
*/
type PutAttributesParams struct {

	/*Accept*/
	Accept *string
	/*ContentType*/
	ContentType *string
	/*Embedded*/
	Embedded *string
	/*Name*/
	Name *string
}

// WithAccept adds the accept to the put attributes params
func (o *PutAttributesParams) WithAccept(accept *string) *PutAttributesParams {
	o.Accept = accept
	return o
}

// WithContentType adds the contentType to the put attributes params
func (o *PutAttributesParams) WithContentType(contentType *string) *PutAttributesParams {
	o.ContentType = contentType
	return o
}

// WithEmbedded adds the embedded to the put attributes params
func (o *PutAttributesParams) WithEmbedded(embedded *string) *PutAttributesParams {
	o.Embedded = embedded
	return o
}

// WithName adds the name to the put attributes params
func (o *PutAttributesParams) WithName(name *string) *PutAttributesParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PutAttributesParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Accept != nil {

		// query param Accept
		var qrAccept string
		if o.Accept != nil {
			qrAccept = *o.Accept
		}
		qAccept := qrAccept
		if qAccept != "" {
			if err := r.SetQueryParam("Accept", qAccept); err != nil {
				return err
			}
		}

	}

	if o.ContentType != nil {

		// query param Content-Type
		var qrContentType string
		if o.ContentType != nil {
			qrContentType = *o.ContentType
		}
		qContentType := qrContentType
		if qContentType != "" {
			if err := r.SetQueryParam("Content-Type", qContentType); err != nil {
				return err
			}
		}

	}

	if o.Embedded != nil {

		// query param _embedded
		var qrEmbedded string
		if o.Embedded != nil {
			qrEmbedded = *o.Embedded
		}
		qEmbedded := qrEmbedded
		if qEmbedded != "" {
			if err := r.SetQueryParam("_embedded", qEmbedded); err != nil {
				return err
			}
		}

	}

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
