package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/swag"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewPutCalendarParams creates a new PutCalendarParams object
// with the default values initialized.
func NewPutCalendarParams() *PutCalendarParams {
	var (
		replaceDefault        bool = bool(false)
		updateTriggersDefault bool = bool(false)
	)
	return &PutCalendarParams{
		Replace:        &replaceDefault,
		UpdateTriggers: &updateTriggersDefault,
	}
}

/*PutCalendarParams contains all the parameters to send to the API endpoint
for the put calendar operation typically these are written to a http.Request
*/
type PutCalendarParams struct {

	/*CalendarName*/
	CalendarName *string
	/*Replace*/
	Replace *bool
	/*UpdateTriggers*/
	UpdateTriggers *bool
}

// WithCalendarName adds the calendarName to the put calendar params
func (o *PutCalendarParams) WithCalendarName(calendarName *string) *PutCalendarParams {
	o.CalendarName = calendarName
	return o
}

// WithReplace adds the replace to the put calendar params
func (o *PutCalendarParams) WithReplace(replace *bool) *PutCalendarParams {
	o.Replace = replace
	return o
}

// WithUpdateTriggers adds the updateTriggers to the put calendar params
func (o *PutCalendarParams) WithUpdateTriggers(updateTriggers *bool) *PutCalendarParams {
	o.UpdateTriggers = updateTriggers
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PutCalendarParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.CalendarName != nil {

		// path param calendarName
		if err := r.SetPathParam("calendarName", *o.CalendarName); err != nil {
			return err
		}

	}

	if o.Replace != nil {

		// query param replace
		var qrReplace bool
		if o.Replace != nil {
			qrReplace = *o.Replace
		}
		qReplace := swag.FormatBool(qrReplace)
		if qReplace != "" {
			if err := r.SetQueryParam("replace", qReplace); err != nil {
				return err
			}
		}

	}

	if o.UpdateTriggers != nil {

		// query param updateTriggers
		var qrUpdateTriggers bool
		if o.UpdateTriggers != nil {
			qrUpdateTriggers = *o.UpdateTriggers
		}
		qUpdateTriggers := swag.FormatBool(qrUpdateTriggers)
		if qUpdateTriggers != "" {
			if err := r.SetQueryParam("updateTriggers", qUpdateTriggers); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
