package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RemoveConnectionDetailsReader is a Reader for the RemoveConnectionDetails structure.
type RemoveConnectionDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *RemoveConnectionDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRemoveConnectionDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemoveConnectionDetailsOK creates a RemoveConnectionDetailsOK with default headers values
func NewRemoveConnectionDetailsOK() *RemoveConnectionDetailsOK {
	return &RemoveConnectionDetailsOK{}
}

/*RemoveConnectionDetailsOK handles this case with default header values.

RemoveConnectionDetailsOK remove connection details o k
*/
type RemoveConnectionDetailsOK struct {
}

func (o *RemoveConnectionDetailsOK) Error() string {
	return fmt.Sprintf("[DELETE /{uuid}][%d] removeConnectionDetailsOK ", 200)
}

func (o *RemoveConnectionDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
