package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRemoveConnectionDetailsParams creates a new RemoveConnectionDetailsParams object
// with the default values initialized.
func NewRemoveConnectionDetailsParams() *RemoveConnectionDetailsParams {
	var ()
	return &RemoveConnectionDetailsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveConnectionDetailsParamsWithTimeout creates a new RemoveConnectionDetailsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoveConnectionDetailsParamsWithTimeout(timeout time.Duration) *RemoveConnectionDetailsParams {
	var ()
	return &RemoveConnectionDetailsParams{

		timeout: timeout,
	}
}

/*RemoveConnectionDetailsParams contains all the parameters to send to the API endpoint
for the remove connection details operation typically these are written to a http.Request
*/
type RemoveConnectionDetailsParams struct {

	/*UUID*/
	UUID *string

	timeout time.Duration
}

// WithUUID adds the uuid to the remove connection details params
func (o *RemoveConnectionDetailsParams) WithUUID(UUID *string) *RemoveConnectionDetailsParams {
	o.UUID = UUID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveConnectionDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.UUID != nil {

		// path param uuid
		if err := r.SetPathParam("uuid", *o.UUID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
