package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewUpdateRoleParams creates a new UpdateRoleParams object
// with the default values initialized.
func NewUpdateRoleParams() *UpdateRoleParams {
	var ()
	return &UpdateRoleParams{}
}

/*UpdateRoleParams contains all the parameters to send to the API endpoint
for the update role operation typically these are written to a http.Request
*/
type UpdateRoleParams struct {

	/*Name*/
	Name *string
}

// WithName adds the name to the update role params
func (o *UpdateRoleParams) WithName(name *string) *UpdateRoleParams {
	o.Name = name
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateRoleParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.Name != nil {

		// path param name
		if err := r.SetPathParam("name", *o.Name); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
