package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateJobsParams creates a new UpdateJobsParams object
// with the default values initialized.
func NewUpdateJobsParams() *UpdateJobsParams {
	var (
		replaceTriggerIgnoreTypeDefault bool = bool(false)
	)
	return &UpdateJobsParams{
		ReplaceTriggerIgnoreType: &replaceTriggerIgnoreTypeDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateJobsParamsWithTimeout creates a new UpdateJobsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateJobsParamsWithTimeout(timeout time.Duration) *UpdateJobsParams {
	var (
		replaceTriggerIgnoreTypeDefault bool = bool(false)
	)
	return &UpdateJobsParams{
		ReplaceTriggerIgnoreType: &replaceTriggerIgnoreTypeDefault,

		timeout: timeout,
	}
}

/*UpdateJobsParams contains all the parameters to send to the API endpoint
for the update jobs operation typically these are written to a http.Request
*/
type UpdateJobsParams struct {

	/*ID*/
	ID *string
	/*ReplaceTriggerIgnoreType*/
	ReplaceTriggerIgnoreType *bool

	timeout time.Duration
}

// WithID adds the id to the update jobs params
func (o *UpdateJobsParams) WithID(ID *string) *UpdateJobsParams {
	o.ID = ID
	return o
}

// WithReplaceTriggerIgnoreType adds the replaceTriggerIgnoreType to the update jobs params
func (o *UpdateJobsParams) WithReplaceTriggerIgnoreType(ReplaceTriggerIgnoreType *bool) *UpdateJobsParams {
	o.ReplaceTriggerIgnoreType = ReplaceTriggerIgnoreType
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateJobsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string
		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {
			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}

	}

	if o.ReplaceTriggerIgnoreType != nil {

		// query param replaceTriggerIgnoreType
		var qrReplaceTriggerIgnoreType bool
		if o.ReplaceTriggerIgnoreType != nil {
			qrReplaceTriggerIgnoreType = *o.ReplaceTriggerIgnoreType
		}
		qReplaceTriggerIgnoreType := swag.FormatBool(qrReplaceTriggerIgnoreType)
		if qReplaceTriggerIgnoreType != "" {
			if err := r.SetQueryParam("replaceTriggerIgnoreType", qReplaceTriggerIgnoreType); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
