package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewUpdateCancelReportExecutionParams creates a new UpdateCancelReportExecutionParams object
// with the default values initialized.
func NewUpdateCancelReportExecutionParams() *UpdateCancelReportExecutionParams {
	var ()
	return &UpdateCancelReportExecutionParams{}
}

/*UpdateCancelReportExecutionParams contains all the parameters to send to the API endpoint
for the update cancel report execution operation typically these are written to a http.Request
*/
type UpdateCancelReportExecutionParams struct {

	/*ExecutionID*/
	ExecutionID *string
}

// WithExecutionID adds the executionId to the update cancel report execution params
func (o *UpdateCancelReportExecutionParams) WithExecutionID(executionId *string) *UpdateCancelReportExecutionParams {
	o.ExecutionID = executionId
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCancelReportExecutionParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	if o.ExecutionID != nil {

		// path param executionId
		if err := r.SetPathParam("executionId", *o.ExecutionID); err != nil {
			return err
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
