package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// UpdatePermissionReader is a Reader for the UpdatePermission structure.
type UpdatePermissionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *UpdatePermissionReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdatePermissionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdatePermissionOK creates a UpdatePermissionOK with default headers values
func NewUpdatePermissionOK() *UpdatePermissionOK {
	return &UpdatePermissionOK{}
}

/*UpdatePermissionOK handles this case with default header values.

UpdatePermissionOK update permission o k
*/
type UpdatePermissionOK struct {
}

func (o *UpdatePermissionOK) Error() string {
	return fmt.Sprintf("[PUT /{uri:.+}][%d] updatePermissionOK ", 200)
}

func (o *UpdatePermissionOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
