package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// UpdatePermissionRootReader is a Reader for the UpdatePermissionRoot structure.
type UpdatePermissionRootReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *UpdatePermissionRootReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdatePermissionRootOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdatePermissionRootOK creates a UpdatePermissionRootOK with default headers values
func NewUpdatePermissionRootOK() *UpdatePermissionRootOK {
	return &UpdatePermissionRootOK{}
}

/*UpdatePermissionRootOK handles this case with default header values.

UpdatePermissionRootOK update permission root o k
*/
type UpdatePermissionRootOK struct {
}

func (o *UpdatePermissionRootOK) Error() string {
	return fmt.Sprintf("[PUT /permissions][%d] updatePermissionRootOK ", 200)
}

func (o *UpdatePermissionRootOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}
