package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command


import (
  "io"
  "net/http"

  "github.com/go-swagger/go-swagger/httpkit"
  "github.com/go-swagger/go-swagger/swag"
  "github.com/go-swagger/go-swagger/errors"
  "github.com/go-swagger/go-swagger/httpkit/validate"
  "github.com/go-swagger/go-swagger/client"

  strfmt "github.com/go-swagger/go-swagger/strfmt"

  "github.com/retrievercommunications/jasperserver-go-client/models"
  
  
)

// UpdateJobReader is a Reader for the UpdateJob structure.
type UpdateJobReader struct {
  formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *UpdateJobReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
  switch response.Code() {
  
    case 200:
      result := NewUpdateJobOK()
      if err := result.readResponse(response, consumer, o.formats); err != nil {
        return nil, err
      }
      return result, nil
  
    default:
      return nil, client.NewAPIError("unknown error", response, response.Code())
  }
}


// NewUpdateJobOK creates a UpdateJobOK with default headers values
func NewUpdateJobOK() *UpdateJobOK {
  return &UpdateJobOK{
    }
}

/*UpdateJobOK handles this case with default header values.

UpdateJobOK update job o k
*/
type UpdateJobOK struct {
  
  
}


func (o *UpdateJobOK) Error() string {
	return fmt.Sprintf("[POST /{id: \d+}][%d] updateJobOK ", 200)
}


func (o *UpdateJobOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {
  
  
  return nil
}





